openapi: 3.0.0
info:
  title: Fiber API
  description: API for interacting with Fiber Network
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local development server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
    
    Success:
      type: object
      properties:
        message:
          type: string
          description: Success message

    Channel:
      type: object
      properties:
        channel_id:
          type: string
          description: Channel ID
        peer_id:
          type: string
          description: Peer ID
        local_balance:
          type: string
          description: Local balance in CKB
        remote_balance:
          type: string
          description: Remote balance in CKB
        offered_tlc_balance:
          type: string
          description: Offered TLC balance in CKB
        received_tlc_balance:
          type: string
          description: Received TLC balance in CKB
        status:
          type: string
          description: Channel status

    Invoice:
      type: object
      properties:
        amount:
          type: string
          description: Amount in CKB
        data:
          type: object
          properties:
            payment_hash:
              type: string
              description: Payment hash
            description:
              type: string
              description: Invoice description

security:
  - BearerAuth: []

paths:
  /fiber/peer/connect:
    post:
      summary: Connect to a peer
      description: Connect to a peer in the Fiber network
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - address
              properties:
                address:
                  type: string
                  description: Peer address to connect to
                save:
                  type: boolean
                  description: Whether to save the peer connection
                  default: true
      responses:
        '200':
          description: Successfully connected to peer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /fiber/channel:
    post:
      summary: Open a new channel
      description: Open a new payment channel with a peer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - peerId
                - fundingAmount
              properties:
                peerId:
                  type: string
                  description: ID of the peer to open channel with
                fundingAmount:
                  type: number
                  description: Amount in CKB to fund the channel
                isPublic:
                  type: boolean
                  description: Whether the channel is public
                  default: true
      responses:
        '200':
          description: Channel creation request sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  channelId:
                    type: string
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /fiber/channels:
    get:
      summary: List channels
      description: Get a list of all channels
      parameters:
        - name: peerId
          in: query
          description: Filter channels by peer ID
          required: false
          schema:
            type: string
        - name: includeClosed
          in: query
          description: Include closed channels in the response
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: List of channels
          content:
            application/json:
              schema:
                type: object
                properties:
                  channels:
                    type: array
                    items:
                      $ref: '#/components/schemas/Channel'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /fiber/channel/{channelId}/close:
    post:
      summary: Close a channel
      description: Close an existing payment channel
      parameters:
        - name: channelId
          in: path
          required: true
          description: ID of the channel to close
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - closeScript
                - feeRate
              properties:
                closeScript:
                  type: object
                  description: Script to use for closing the channel
                  required:
                    - code_hash
                    - hash_type
                    - args
                  properties:
                    code_hash:
                      type: string
                    hash_type:
                      type: string
                    args:
                      type: string
                force:
                  type: boolean
                  description: Force close the channel
                  default: false
                feeRate:
                  type: string
                  description: Fee rate for closing transaction
      responses:
        '200':
          description: Channel close request sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /fiber/transfer:
    post:
      summary: Transfer CKB using invoice
      description: Transfer CKB using a Fiber invoice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - invoice
                - amountInCKB
              properties:
                invoice:
                  type: string
                  description: Fiber invoice string
                amountInCKB:
                  type: number
                  description: Amount to transfer in CKB
                channelId:
                  type: string
                  description: Channel ID to use for transfer (optional if JOYID_PEER_ID is set)
      responses:
        '200':
          description: Transfer initiated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  tlcId:
                    type: string
                    description: ID of the created TLC
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /fiber/parse-invoice:
    post:
      summary: Parse a Fiber invoice
      description: Parse and validate a Fiber invoice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - invoice
              properties:
                invoice:
                  type: string
                  description: Fiber invoice string to parse
      responses:
        '200':
          description: Parsed invoice
          content:
            application/json:
              schema:
                type: object
                properties:
                  invoice:
                    $ref: '#/components/schemas/Invoice'
        '400':
          description: Invalid invoice format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
