openapi: 3.0.0
info:
  title: Fiber RPC API
  description: |
    JSON-RPC API for interacting with Fiber Node. All requests are POST requests to the root endpoint (/).
    Each request must follow the JSON-RPC 2.0 specification with the following format:
    ```json
    {
      "jsonrpc": "2.0",
      "method": "method_name",
      "params": [{ ... }],
      "id": 1
    }
    ```
  version: 1.0.0

servers:
  - url: http://localhost:8228
    description: Local Fiber node

components:
  schemas:
    JsonRpcRequest:
      type: object
      required:
        - jsonrpc
        - method
        - params
        - id
      properties:
        jsonrpc:
          type: string
          enum: ['2.0']
        method:
          type: string
        params:
          type: array
          items:
            type: object
        id:
          type: integer

    JsonRpcResponse:
      type: object
      required:
        - jsonrpc
        - id
      properties:
        jsonrpc:
          type: string
          enum: ['2.0']
        result:
          type: object
        error:
          type: object
          properties:
            code:
              type: integer
            message:
              type: string
        id:
          type: integer

    Script:
      type: object
      properties:
        code_hash:
          type: string
        hash_type:
          type: string
          enum: ['type', 'data', 'data1']
        args:
          type: string

    Channel:
      type: object
      properties:
        channel_id:
          type: string
        is_public:
          type: boolean
        channel_outpoint:
          type: string
        peer_id:
          type: string
        funding_udt_type_script:
          $ref: '#/components/schemas/Script'
        state:
          type: object
          properties:
            state_name:
              type: string
            state_flags:
              type: array
              items:
                type: string
        local_balance:
          type: string
        offered_tlc_balance:
          type: string
        remote_balance:
          type: string
        received_tlc_balance:
          type: string
        latest_commitment_transaction_hash:
          type: string
        created_at:
          type: string

    PaymentResponse:
      type: object
      required:
        - payment_hash
        - status
        - created_at
        - last_updated_at
        - fee
      properties:
        payment_hash:
          type: string
          description: The payment hash
        status:
          type: string
          enum: ['pending', 'succeeded', 'failed']
          description: The status of the payment
        created_at:
          type: string
          description: Creation timestamp in hex format (milliseconds from UNIX epoch)
        last_updated_at:
          type: string
          description: Last update timestamp in hex format (milliseconds from UNIX epoch)
        failed_error:
          type: string
          description: Error message if payment failed
        fee:
          type: string
          description: Fee paid for the payment in hex format

paths:
  /:
    post:
      summary: JSON-RPC endpoint
      description: All Fiber RPC methods are called through this endpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                # Peer Module
                - allOf:
                    - $ref: '#/components/schemas/JsonRpcRequest'
                    - type: object
                      properties:
                        method:
                          enum: ['connect_peer']
                        params:
                          type: array
                          items:
                            type: object
                            required: ['address']
                            properties:
                              address:
                                type: string
                                description: Peer multiaddr
                              save:
                                type: boolean
                                default: false

                - allOf:
                    - $ref: '#/components/schemas/JsonRpcRequest'
                    - type: object
                      properties:
                        method:
                          enum: ['disconnect_peer']
                        params:
                          type: array
                          items:
                            type: object
                            required: ['peer_id']
                            properties:
                              peer_id:
                                type: string

                # Channel Module
                - allOf:
                    - $ref: '#/components/schemas/JsonRpcRequest'
                    - type: object
                      properties:
                        method:
                          enum: ['open_channel']
                        params:
                          type: array
                          items:
                            type: object
                            required: ['peer_id', 'funding_amount']
                            properties:
                              peer_id:
                                type: string
                              funding_amount:
                                type: string
                                description: Amount in hex format
                              public:
                                type: boolean
                                default: true
                              funding_udt_type_script:
                                $ref: '#/components/schemas/Script'

                - allOf:
                    - $ref: '#/components/schemas/JsonRpcRequest'
                    - type: object
                      properties:
                        method:
                          enum: ['list_channels']
                        params:
                          type: array
                          items:
                            type: object
                            properties:
                              peer_id:
                                type: string
                              include_closed:
                                type: boolean

                - allOf:
                    - $ref: '#/components/schemas/JsonRpcRequest'
                    - type: object
                      properties:
                        method:
                          enum: ['add_tlc']
                        params:
                          type: array
                          items:
                            type: object
                            required: ['channel_id', 'amount', 'payment_hash']
                            properties:
                              channel_id:
                                type: string
                              amount:
                                type: string
                                description: Amount in hex format
                              payment_hash:
                                type: string
                              expiry:
                                type: string
                                description: Expiry timestamp in hex format
                              hash_algorithm:
                                type: string
                                enum: ['sha256']
                                default: 'sha256'

                - allOf:
                    - $ref: '#/components/schemas/JsonRpcRequest'
                    - type: object
                      properties:
                        method:
                          enum: ['remove_tlc']
                        params:
                          type: array
                          items:
                            type: object
                            required: ['channel_id', 'tlc_id', 'reason']
                            properties:
                              channel_id:
                                type: string
                              tlc_id:
                                type: string
                              reason:
                                type: object
                                required: ['payment_preimage']
                                properties:
                                  payment_preimage:
                                    type: string

                - allOf:
                    - $ref: '#/components/schemas/JsonRpcRequest'
                    - type: object
                      properties:
                        method:
                          enum: ['shutdown_channel']
                        params:
                          type: array
                          items:
                            type: object
                            required: ['channel_id', 'close_script', 'fee_rate']
                            properties:
                              channel_id:
                                type: string
                              close_script:
                                $ref: '#/components/schemas/Script'
                              force:
                                type: boolean
                                default: false
                              fee_rate:
                                type: string
                                description: Fee rate in hex format
                                default: '0x3f2'

                # Invoice Module
                - allOf:
                    - $ref: '#/components/schemas/JsonRpcRequest'
                    - type: object
                      properties:
                        method:
                          enum: ['new_invoice']
                        params:
                          type: array
                          items:
                            type: object
                            required: ['amount', 'currency', 'payment_preimage']
                            properties:
                              amount:
                                type: string
                                description: Amount in hex format
                              description:
                                type: string
                              currency:
                                type: string
                                enum: ['fibb', 'fibt', 'fibd']
                              payment_preimage:
                                type: string
                              expiry:
                                type: string
                                description: Expiry duration in hex format (seconds)
                              hash_algorithm:
                                type: string
                                enum: ['sha256']
                                default: 'sha256'

                - allOf:
                    - $ref: '#/components/schemas/JsonRpcRequest'
                    - type: object
                      properties:
                        method:
                          enum: ['parse_invoice']
                        params:
                          type: array
                          items:
                            type: object
                            required: ['invoice']
                            properties:
                              invoice:
                                type: string
                                description: Invoice string to parse

                # Payment Module
                - allOf:
                    - $ref: '#/components/schemas/JsonRpcRequest'
                    - type: object
                      properties:
                        method:
                          enum: ['send_payment']
                        params:
                          type: array
                          items:
                            type: object
                            properties:
                              target_pubkey:
                                type: string
                                description: The identifier of the payment target
                              amount:
                                type: string
                                description: Amount in hex format
                              payment_hash:
                                type: string
                                description: The hash to use within the payment's HTLC
                              final_tlc_expiry_delta:
                                type: string
                                description: TLC expiry delta for the final hop in milliseconds (hex)
                              tlc_expiry_limit:
                                type: string
                                description: TLC expiry limit for the whole payment in milliseconds (hex)
                              invoice:
                                type: string
                                description: The encoded invoice to send to the recipient
                              timeout:
                                type: string
                                description: Payment timeout in seconds (hex)
                              max_fee_amount:
                                type: string
                                description: Maximum fee amounts in shannons (hex)
                              max_parts:
                                type: string
                                description: Max parts for multi-part payments (hex)
                              keysend:
                                type: boolean
                                description: Keysend payment
                              udt_type_script:
                                $ref: '#/components/schemas/Script'
                                description: UDT type script for the payment
                              allow_self_payment:
                                type: boolean
                                description: Allow self payment
                                default: false
                              dry_run:
                                type: boolean
                                description: Dry run for payment validation
                                default: false

                - allOf:
                    - $ref: '#/components/schemas/JsonRpcRequest'
                    - type: object
                      properties:
                        method:
                          enum: ['get_payment']
                        params:
                          type: array
                          items:
                            type: object
                            required: ['payment_hash']
                            properties:
                              payment_hash:
                                type: string
                                description: The payment hash to retrieve

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonRpcResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonRpcResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonRpcResponse'
